### ISSUE TITLE
Uncaught Error: Class 'Parsedown' not found

### ISSUE THREAD

**Issue by KittMedia** [florianbrinkmann/slack-to-wordpress-converter#2]
By using this file via cli out of the box I get the following error message:

```
Fatal error: Uncaught Error: Class 'Parsedown' not found in /dev/slack-to-wordpress-converter/slack-to-wordpress-converter.php on line 491

Error: Class 'Parsedown' not found in /dev/slack-to-wordpress-converter/slack-to-wordpress-converter.php on line 491

Call Stack:
    0.0067     640776   1. {main}() /dev/slack-to-wordpress-converter/slack-to-wordpress-converter.php:0
```

I first needed to get Parsedown via composer and autoload it in the `slack-to-WordPress-converter.php` to get it working.

**Comment by florianbrinkmann** [comment]
Ah, so the file was there for a reason locally and not part of my started refactoring :D Thanks for your report! Will fix that.

**Comment by florianbrinkmann** [comment]
@KittMedia should be fixed now – added Composer and created a release (https://github.com/florianbrinkmann/slack-to-wordpress-converter/releases) for easy downloading without the need of running composer :)
Would great if you could give it a try.

**Comment by KittMedia** [comment]
Works fine now! Thank you 🙂

**Comment by florianbrinkmann** [comment]
Great, thanks for testing it :)
